[package]
name = "serde-m3u"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["ahaoboy"]
repository = "https://github.com/ahaoboy/serde-m3u"
description = "serde-m3u"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"