[package]
name = "serde-m3u"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["ahaoboy"]
repository = "https://github.com/ahaoboy/serde-m3u"
description = "serde-m3u"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"